### ISSUE TITLE
Standard input for pdos plot

### ISSUE THREAD

**Issue by unkcpz** [osscar-org/widget-bandsplot#10]
I summarize the format used currently for bandsplot, with some ideas to standardize it. Please find the doc at https://docs.google.com/document/d/1pM93cMeU1U8A6btzE4O9T7WLwIMJNRZa7N3n2QJlkTM/edit?usp=sharing (let me know if you think it is valuable to make it public).

@dou-du @mbercx @giovannipizzi

[bandsdata_Co.txt](https://github.com/osscar-org/widget-bandsplot/files/8861436/bandsdata_Co.txt)
~~[pdosdata_Co_spins_tdos.txt](https://github.com/osscar-org/widget-bandsplot/files/8861437/pdosdata_Co_spins_tdos.txt)~~
(2022-07-01) ~~[pdosdata_Co_spins_tdos_pdos.txt](https://github.com/osscar-org/widget-bandsplot/files/9031357/pdosdata_Co_spins_tdos_pdos.txt)~~

EDIT: the format is proposed in https://github.com/osscar-org/widget-bandsplot/pull/11

**Comment by dou-du** [comment]
The new format of the DOS json files are in the "example/data" folder.

**Comment by unkcpz** [comment]
Sorry @dou-du , which file exactly? You mean you have implement it and can plot with the new pdos format? I'd really appreciate it if you can have me review it by a PR, thanks!

**Comment by dou-du** [comment]
Here is the new DOS file:

https://github.com/osscar-org/widget-bandsplot/blob/develop/example/data/Co_dos.json

The new release widget version is 0.3.5.

**Comment by unkcpz** [comment]
Hi @dou-du, I think this input is **NOT** what we discussed and decided to adopt in the aiidalab meeting. First of all, I think we agree that `tdos` and different obitals of `pdos` should be in the same layer of the dictionary. Second, if I remembered correctly, what @yakutovicha advised at the end of the meeting was we keep one x data for all orbitals, and allow to set x data for different orbitals respectively with sector x and y data (so that y can drop lots of `0.00` in the data) as optional.

That's why I need to open PR for this, so instead of lots of back and forth, we can iterate about the issues much faster.

**Comment by dou-du** [comment]
> Hi @dou-du, I think this input is **NOT** what we discussed and decided to adopt in the aiidalab meeting.
> 
> * First of all, I think we agree that `tdos` and different obitals of `pdos` should be in the same layer of the dictionary.
> * Second (not urgent but good to have, so can be tackled by another PR), if I remembered correctly, what @yakutovicha advised at the end of the meeting was we keep one x data for all orbitals, and allow to set x data for different orbitals respectively with sector x and y data (so that y can drop lots of `0.00` in the data) as optional.
> 
> That's why I need you to open PR for this, so instead of lots of back and forth, we can iterate about the issues much faster.

Hi Jusong,

1. I do not understand that tdos and pdos are not in the same layer. The json file has them in the equivalent deep.

2. I think twice for the simplicity and generality of the json file. No one is going to plot hundred of pdos in the figures. Including x for all data will make it much easier 
and not making any problem. 

Generally, all DOS results can be converted into this format with a simple Python script. The format of this json file is a matter of taste. I do not want to change it again unless there really exist issues. You also agreed to let me decide the format.

We should focus on the functionality of the widget instead.

**Comment by unkcpz** [comment]
Hi @dou-du , thanks a lot for your effort on this. 

> We should focus on the functionality of the widget instead.

I agree we should focus on the functionality, the fact is extensibility and making the widget user-friendly is also an important part of the functionality. 

> I do not understand that tdos and pdos are not in the same layer.

Please have a look at https://github.com/osscar-org/widget-bandsplot/pull/11, the format I proposed, if you disagree, let's discuss it there. Let me know if there are some difficulties in implementing js code for that format.

> I think twice for the simplicity and generality of the json file. No one is going to plot hundred of pdos in the figures. Including x for all data will make it much easier and not making any problem.

We can leave this in the future, not mandatory.

> The format of this json file is a matter of taste. I do not want to change it again unless there really exist issues.

The format matters! Please check if the following use cases are supported or not:
1. if user don't have total dos but only pdos of some orbitals?
2. if user only want to plot total dos?
3. if user want to plot integral dos of some orbitals, where to put these data?
4. you don't read label for total dos, what if user what to change its value?

Best,
Jason

**Comment by dou-du** [comment]
> Hi @dou-du , thanks a lot for your effort on this. I also want to make progress on this and move to the issue of plotting multiple band structures, which I needed for the SSSP app.
> 
> > You also agreed to let me decide the format.
> 
> I think it is all fine there were misunderstandings in the implementation details, That is why I ask you _MANY TIMES_ to open a PR and ask me to have a look.
> 
> > We should focus on the functionality of the widget instead.
> 
> I agree we should focus on the functionality, the fact is extensibility and making the widget user-friendly is also an important part of the functionality.
> 
> > I do not understand that tdos and pdos are not in the same layer.
> 
> I wrote "`tdos` and **different obitals of `pdos`** should be in the same layer of the dictionary". Please have a look at #11, the format I proposed, if you disagree, let's discuss it there. Let me know if there are some difficulties in implementing js code for that format.
> 
> > I think twice for the simplicity and generality of the json file. No one is going to plot hundred of pdos in the figures. Including x for all data will make it much easier and not making any problems.
> 
> We can leave this in the future, not mandatory.
> 
> > The format of this json file is a matter of taste. I do not want to change it again unless there really exist issues.
> 
> The format matters! And there are existing issues with your format. Please check if the following use cases are supported by what you implemented or not:
> 
> 1. if the user doesn't have total dos but only pdos of some orbitals?
> 2. if the user only wants to plot total dos?
> 3. if the user wants to plot integral dos of some orbitals, where to put these data?
> 4. you don't read labels for total dos, what if the user what to change its value?
> 
> These are all not a problem if using the format I proposed (also it is the format I thought everyone agreed on in aiidalab meeting).
> 
> Best, Jason

Hi Jason,

Thanks! Yes, I agreed have a tdos will cause problem if it is not given. However, I do not like your proposed json file either. There is no need to have key for different pdos and it make harder to implement. Instead, I gave a new json file in PR #13 . Please have a look.

Best, Dou

**Comment by unkcpz** [comment]
> There is no need to have key for different pdos and it make harder to implement. Instead, I gave a new json file in PR https://github.com/osscar-org/widget-bandsplot/pull/13 . Please have a look.

thanks! Could you elaborate on why it is hard to implement? 
That is the format I was thinking about. The pro is we do not need the unused key for every orbital. 
I didn't use it since when users look at the JSON content, for example using vscode, if every orbital is a JSON property it is easy to fold it and see from the text editor which one it is (check the figure below). But look it again, I think it is not quite useful. 

If someone else has no objection, I agree with the format proposed by @dou-du at #13. Pinning @giovannipizzi @yakutovicha for comments. 

![image](https://user-images.githubusercontent.com/8831685/184387407-4d5c8e86-f9b0-4d2d-8037-4ff68f86deb0.png)
