### ISSUE TITLE
Update the release flow

### ISSUE THREAD

**Issue by unkcpz** [osscar-org/widget-bandsplot#12]
If I understand correctly, it requires releasing both widget-bandsplot pypi package and npm package when the code change. 
@dou-du I am familiar with pypi flow but not npm, can you explain the relation between these two? They are independent or pypi rely on the npm package? 

Anyways, we can put the release flow into CI action to make this more convenient.

**Comment by dou-du** [comment]
> If I understand correctly, it requires releasing both widget-bandsplot pypi package and npm package when the code change. @dou-du I am familiar with pypi flow but not npm, can you explain the relation between these two? They are independent or pypi rely on the npm package?
> 
> Anyways, we can put the release flow into CI action to make this more convenient.

Release the npm package for the widget is not necessary. And one cannot install the widget correct with only the npm package. We should only release the PyPi package for the widgets.

**Comment by unkcpz** [comment]
I am confused about this. I think we want to have not only the python widget but also the js code can be used as a REACT component in Materials Cloud. We need to keep the npm package updated. 
If I understand correctly about the logic, we probably can try to keep the version number same for npm js package and pypi package. Both build and release from a github action.

**Comment by dou-du** [comment]
> I am confused about this. I think we want to have not only the python widget but also the js code can be used as a REACT component in Materials Cloud. We need to keep the npm package updated. If I understand correctly about the logic, we probably can try to keep the version number same for npm js package and pypi package. Both build and release from a github action.

Sorry, I am thinking about releasing the npm for this widget (It is another story). Now, I got your question. The javascript library is in the materials cloud repository.

https://github.com/materialscloud-org/bands-widget

I did not take the charge to release this npm package. We should ask Giovanni who have the npm token to release the package.

**Comment by unkcpz** [comment]
Hi @dou-du, any update on this? Did you check the materials cloud ansible repo for this credential? It must be somewhere, or we need to recover the password and update the token. 
Also pinning @eimrek here for any update.

**Comment by dou-du** [comment]
> Hi @dou-du, any update on this? Did you check the materials cloud ansible repo for this credential? It must be somewhere, or we need to recover the password and update the token. Also pinning @eimrek here for any update.

I do not see it in the ansible repository.
