### ISSUE TITLE
Issues and suggestions for the widget

### ISSUE THREAD

**Issue by dou-du** [osscar-org/widget-bandsplot#2]
Please write down your suggestions for this widget. Thanks.

**Comment by csadorf** [comment]
Great job! I am currently trying to integrate the widgets into the QE app. Here are some preliminary suggestions:

 - Rename the `Bandsplot` class to `BandsPlotWidget`.
 - Allow the stand-alone representation of both bands and dos. That means either the `bands` and the `dos` parameters can be `None` (but not both). In case that both are `None`, a `ValueError` should be raised.
 - Rename the `show_fermi` parameter to `plot_fermi_energy` to increase consistency between parameter names and I believe this would be a slightly more accurate description, right?
 - Rename the `ylim` parameter to `y_range` and have it accept a 2-tuple like bokeh, see example here: https://docs.bokeh.org/en/latest/docs/user_guide/plotting.html#raw-rgba-data

**Comment by dou-du** [comment]
> Great job! I am currently trying to integrate the widgets into the QE app. Here are some preliminary suggestions:
> 
> * Rename the `Bandsplot` class to `BandsPlotWidget`.
> * Allow the stand-alone representation of both bands and dos. That means either the `bands` and the `dos` parameters can be `None` (but not both). In case that both are `None`, a `ValueError` should be raised.
> * Rename the `show_fermi` parameter to `plot_fermi_energy` to increase consistency between parameter names and I believe this would be a slightly more accurate description, right?
> * Rename the `ylim` parameter to `y_range` and have it accept a 2-tuple like bokeh, see example here: https://docs.bokeh.org/en/latest/docs/user_guide/plotting.html#raw-rgba-data

Thanks for the suggestions. I will implement them as soon as possible.

**Comment by csadorf** [comment]
@dou-du Do you have an update on this?

**Comment by dou-du** [comment]
> @dou-du Do you have an update on this?

There are still some small things needs to be fixed. It should be ready by tomorrow.
