### ISSUE TITLE
Modernise setup.py

### ISSUE THREAD

**Issue by yakutovicha** [osscar-org/widget-bandsplot#20]
Looking at the code, I think the setup part could be improved.

For instance, we don't need `requirements.txt` and `requirements_test.txt`. The requirements can be put in one file `setup.cfg`. For an example, check [`setup.cfg`](https://github.com/aiidalab/aiidalab/blob/main/setup.cfg) and [`setup.py`](https://github.com/aiidalab/aiidalab/blob/main/setup.py) from the https://github.com/aiidalab/aiidalab repo.

**Comment by unkcpz** [comment]
@yakutovicha thanks! I also thought about this, but the `requirements.txt` is needed for the binder and as a dokku service along with `Procfile`. So we have to either using modernized `setup.cfg` and `setup.py` to keep the duplicated dependency both in `requirements.txt` and `setup.cfg`, or we use the the current "non-mordernized" setup.py.
