### ISSUE TITLE
Documentation for the json inputs format and example notebook to run on binder.

### ISSUE THREAD

**Issue by unkcpz** [osscar-org/widget-bandsplot#21]
- [x] @dou-du add to README me how to use the widget
- [ ] Add the exception type per schema validation and if none of the inputs are given.

**Comment by unkcpz** [comment]
Hi @dou-du, do you get time to work on this? I think it is valuable to have a section on README to tell the user how to use this widget and what the input format is rather than reference the example notebook to check how to use it.

**Comment by dou-du** [comment]
> Hi @dou-du, do you get time to work on this? I think it is valuable to have a section on README to tell the user how to use this widget and what the input format is rather than reference the example notebook to check how to use it.

Ok, I will do it now.

**Comment by dou-du** [comment]
> > Hi @dou-du, do you get time to work on this? I think it is valuable to have a section on README to tell the user how to use this widget and what the input format is rather than reference the example notebook to check how to use it.
> 
> Ok, I will do it now.

Rethink about this, I think the best solution is using binder, which let the users to read and try the widget with the JupyterLab. I think that it's probably not necessary to describe the usage in the README file. We can mention that the usage is in the Binder link. @unkcpz @csadorf @giovannipizzi

**Comment by csadorf** [comment]
@dou-du Please add to the README:
- [ ] a short code snippet example on how the widget is used within a notebook
- [ ] a short paragraph that mentions how to use the example notebooks (that includes instructions on how to setup an appropriate environment!)
- [ ] a paragraph on how to open the notebook in binder with a link. Please also add a binder badge at the top of the README next to the PyPI badge. 

Thanks.

**Comment by dou-du** [comment]
> @dou-du Please add to the README:
> 
> * [x]  a short code snippet example on how the widget is used within a notebook
> * [ ]  a short paragraph that mentions how to use the example notebooks (that includes instructions on how to setup an appropriate environment!)
> * [x]  a paragraph on how to open the notebook in binder with a link. Please also add a binder badge at the top of the README next to the PyPI badge.
> 
> Thanks.

I have already implemented in the binder branch, which is merged yet. You can check it on the binder branch.
