### ISSUE TITLE
The widget not working on the notebook example

### ISSUE THREAD

**Issue by unkcpz** [osscar-org/widget-bandsplot#22]
I run the notebook example and the widget does not correctly show the results. 
I guess it is the same reason that https://osscar-widgets.matcloud.xyz/voila/render/bandsplot/widget-bandsplot.ipynb not showing the plot. This basically break all the functionality of the widget. 
@dou-du do you have any clue why this is happening? 

My matplotlib version is `3.5,2` and `3.4.3` and I try two `ipympl` version `0.8.3` and `0.9.2`. Neither of their combinations works.

**Comment by dou-du** [comment]
@unkcpz Hi Jusong, could you review the binder link and close this issue? Thanks!

**Comment by unkcpz** [comment]
Hi @dou-du, sure. Always feel free to close the issue if you think it is fixed. Unlike the PRs, the issue is easy to be reopened.
