### ISSUE TITLE
Allow customisation of colors

### ISSUE THREAD

**Issue by giovannipizzi** [osscar-org/widget-bandsplot#25]
Colors should not be hardcoded, even if we change them based on some request, we'll always have someone unhappy.
The current ones should be defaults, but there shoudd be ways to change them. Ideally as similar as possible to te way it's done inside the JS code. But for instance, via a dictionary:
```python
{
   "dos": {
      "CoS up": "#123456",
      ...
   },
   "bands": {
       "up": "#123456",
       "down": "#123456",
       "both": "#123456"
   }
}
```

**Comment by dou-du** [comment]
> Colors should not be hardcoded, even if we change them based on some request, we'll always have someone unhappy. The current ones should be defaults, but there shoudd be ways to change them. Ideally as similar as possible to te way it's done inside the JS code. But for instance, via a dictionary:
> 
> ```python
> {
>    "dos": {
>       "CoS up": "#123456",
>       ...
>    },
>    "bands": {
>        "up": "#123456",
>        "down": "#123456",
>        "both": "#123456"
>    }
> }
> ```

I think you are referring the colors for the bandstructure. Currently, one can custom the colors for the DOS. We will also add color options for bands data.

**Comment by dou-du** [comment]
Now, both colors for bandstructure and DOS can be customed from the Json input files.
