### ISSUE TITLE
Odd module name 'example.py'

### ISSUE THREAD

**Issue by csadorf** [osscar-org/widget-bandsplot#4]
I am a bit confused why there is a module called `example.py` that appears to do "real" work for this package. Is this just a misnomer or why is this module called like that?

https://github.com/osscar-org/widget-bandsplot/blob/develop/widget_bandsplot/example.py

**Comment by dou-du** [comment]
> I am a bit confused why there is a module called `example.py` that appears to do "real" work for this package. Is this just a misnomer or why is this module called like that?
> 
> https://github.com/osscar-org/widget-bandsplot/blob/develop/widget_bandsplot/example.py

This is the default in the cookiecutter template. You are right. I will give a better name. Thanks.
