### ISSUE TITLE
👌  IMPROVE: Provide support for spin-polarised results

### ISSUE THREAD

**Issue by mbercx** [osscar-org/widget-bandsplot#8]
Currently the widget can already plot band structures for spin-polarised systems, distinguishing between up and down states. However, there is no such support for the (P)DOS. The conventional way to show spin up and down together in one DOS plot is to show them on different sides of the zero axis, for example:

![Screenshot 2022-05-03 at 09 28 40](https://user-images.githubusercontent.com/25607960/166418104-c679d111-de41-4eb7-a0fb-9547b81d8a20.png)

One thing to consider in this is that @unkcpz also would like to be able to compare band structures/PDOS for (at least two) different structures. With this in mind, I would suggest that up and down states are plotted in different (customisable) colors for the band structure. For the PDOS, we need different colors to distinguish the type of orbitals used for the projections, but again the side of the axis the plot is on can be used to distinguish up and down states. If we only use different colors, different line types can be used to separate the different plots for the structures.

Comments most welcome! Will adapt the OP as we converge on a final version, and then clearly write down the changes that must be made.

**Comment by mbercx** [comment]
@giovannipizzi we all more or less agree on the above approach for plotting the band structure/PDOS of spin-polarised systems. Do you still have any comments?

**Comment by giovannipizzi** [comment]
Thanks, OK with me - let's see once implemented how this looks like for a PDOS with spin!

**Comment by unkcpz** [comment]
The pdos shown by @dou-du can be found from https://github.com/osscar-org/widget-bandsplot/issues/9. I will test it on QeApp once there is a new bandsplot widget released.
