### ISSUE TITLE
The scale of dos is not properly set

### ISSUE THREAD

**Issue by unkcpz** [osscar-org/widget-bandsplot#9]
When inspecting DOS calculation output in aiidalab-qe app for some structure, the scale of DOS plot is not properly set in widget which leave the total-DOS quite small. Although the shape is correct but user has no way to zoom in and check the details of DOS w.r.t to x-axis 'intensity' of density.  As you can see from the figure attached. I also attached the json file that can directly input to the widget using the example of https://github.com/osscar-org/widget-bandsplot/tree/develop/example. You need rename txt to json. 

![image](https://user-images.githubusercontent.com/8831685/166435873-9fefd54b-b8db-4f85-abf3-3e6fd099c482.png)

[Au_dos.txt](https://github.com/osscar-org/widget-bandsplot/files/8609835/Au_dos.txt)

**Comment by unkcpz** [comment]
Please reopen the issue and attach a screenshot of what you have got with the new fixes. Thanks!

**Comment by dou-du** [comment]
> Please reopen the issue and attach a screenshot of what you have got with the new fixes. Thanks!

Hi Jusong, please have a look at the figure shown below. Thanks!

![Screenshot from 2022-06-28 08-59-35](https://user-images.githubusercontent.com/56022756/176064495-aa7a5b0f-389f-4306-a39f-78102d0ac078.png)

**Comment by unkcpz** [comment]
Looks great, Thanks! 
Once you release a new version and I tested on QeApp we close this issue.

**Comment by dou-du** [comment]
> Looks great, Thanks! Once you release a new version and I tested on QeApp we close this issue.

Thanks! The updated version is 0.3.1. Could you test whether it is working?

**Comment by unkcpz** [comment]
Hi @dou-du, unfortunately, it is not working. I think you did not use the last file I sent to you (also my fault that I did not update the file in https://github.com/osscar-org/widget-bandsplot/issues/10). That's why I suggest you open a PR and I can review it. 

I update the file so you can have another modification.

**Comment by giovannipizzi** [comment]
I think it's also important to allow people to zoom the y axis (x axis when shown close to the band structure) for the (P)DOS plot. Currently one can only zoom the energy axis (connected to the band structure energy axis) and not the DOS axis. One way could be to have an additional slider to change the zoom, or allow for rectangular selection (rather than just along one axis) for the DOS

**Comment by dou-du** [comment]
> I think it's also important to allow people to zoom the y axis (x axis when shown close to the band structure) for the (P)DOS plot. Currently one can only zoom the energy axis (connected to the band structure energy axis) and not the DOS axis. One way could be to have an additional slider to change the zoom, or allow for rectangular selection (rather than just along one axis) for the DOS

Move to issue #31
